export const initialState = {
  userId: 4911600286,
  posts: {
    data: [
      { 
        id: 1,
        image: 'camera.jpg',
        title: 'Sony Alpha A7S 12.2MP Digital Camera',
        description: 'Condition is almost mint.. only minor tripod scratches on the bottom (please see picture).',
        price: 550,
        contact: 'John',
        mail: 'john.doe@example.com',
        phone: '(711) 265-9193',
        userId: 4911600286,
      },
      { 
        id: 2,
        image: 'car.jpg',
        title: '1967 FORD MUSTANG 1968 FASTBACK MUSTANG V8 5.8',
        description: 'The Essex Car Group Ltd are delighted to offer this Stunning 1967 Ford Mustang.',
        price: 75000,
        contact: 'Jane',
        mail: 'jane.doe@example.com',
        phone: '(675) 844-7400',
        userId: 9226564204,
      },
      { 
        id: 3,
        image: 'console.jpg',
        title: 'Sony Playstation One Console 2 Controllers',
        description: 'Sony Playstation One Console With Main Lead & 2 x Controllers. Good condition',
        price: 40,
        contact: 'Jane',
        mail: 'jane.doe@example.com',
        phone: '(675) 844-7400',
        userId: 9226564204,
      },
      { 
        id: 4,
        image: 'watch.jpg',
        title: 'Bulova Quartz Marine Star Chronograph',
        description: 'Good used condition few light scratches and blemishes.',
        price: 150,
        contact: 'Jane',
        mail: 'jane.doe@example.com',
        phone: '(675) 844-7400',
        userId: 9226564204,
      },
      { 
        id: 5,
        image: 'laptop.jpg',
        title: '2015 Macbook Pro. i7,16gb Ram. 500g Hard Drive. New battery!',
        description: 'Mid 2015 Apple Macbook Pro. New Battery fitted 3rd September 2020.',
        price: 900,
        contact: 'John',
        mail: 'john.doe@example.com',
        phone: '(711) 265-9193',
        userId: 4911600286,
      },
      {
        id: 6,
        image: 'phone.jpg',
        title: 'Apple iPhone 5 mobile phone unlocked',
        description: 'This item is in excellent condition and would be great to use as a work phone, etc.',
        price: 60,
        contact: 'John',
        mail: 'john.doe@example.com',
        phone: '(711) 265-9193',
        userId: 4911600286,
      },
    ],
    loading: {
      active: false,
      error: false,
    },
  },
};
